<?php namespace JF;
/**

Copyright 2017 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-e48745
Date:    2017-10-30 13:21:29
Version: v2.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-e48745",
    "email": {
        "to": "scottmsandie@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "new submission",
        "template": ""
    },
    "admin": {
        "users": "admin:b9323",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "blue"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [
        {
            "disabled": false,
            "action": "show",
            "selector": "f9",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "Yes"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f20",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f8",
                    "condition": "==",
                    "value": "No"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f18",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f20",
                    "condition": "==",
                    "value": "Android"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f19",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f20",
                    "condition": "==",
                    "value": "Iphone"
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f10",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f9",
                    "condition": "==",
                    "value": "Gain access to Haiku or Canto."
                }
            ]
        },
        {
            "disabled": false,
            "action": "show",
            "selector": "f21,f22",
            "match": "any",
            "rules": [
                {
                    "disabled": false,
                    "selector": "f10",
                    "condition": "==",
                    "value": "No"
                }
            ]
        }
    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "Bob Smith",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Net ID:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-pencil"
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": ""
                    }
                },
                "placeholder": "abc123"
            },
            "id": "f23",
            "cid": "c100"
        },
        {
            "label": "Have you installed MDM",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": ""
            },
            "id": "f8",
            "cid": "c53"
        },
        {
            "label": "Do you use Android or Iphone",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Android",
                        "checked": false
                    },
                    {
                        "label": "Iphone",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "hidden": true
            },
            "id": "f20",
            "cid": "c61"
        },
        {
            "label": "<a href=\"https:\/\/play.google.com\/store\/apps\/details?id=com.zenprise\">Download MDM for Android<\/a>",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "hidden": true
            },
            "id": "f18",
            "cid": "c53"
        },
        {
            "label": "<a href=https:\/\/itunes.apple.com\/us\/app\/worx-home-by-citrix\/id434682528?mt=8\">Download MDM for Iphone<\/a>",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "hidden": true
            },
            "cid": "c58",
            "id": "f19"
        },
        {
            "label": "What would you like to do?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Gain access to Haiku or Canto.",
                        "checked": false
                    },
                    {
                        "label": "Add fingerprint access to my device.",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "hidden": true,
                "description": "If you want to \"Add fingerprint access to my device\" make your selection and click \"submit\"."
            },
            "id": "f9",
            "cid": "c63"
        },
        {
            "label": "Do you currently have Haiku or Canto installed on your device?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "hidden": true
            },
            "id": "f10",
            "cid": "c68"
        },
        {
            "label": "<a href=\"https:\/\/play.google.com\/store\/apps\/details?id=com.epic.haiku.android\">Download Haiku for Android<\/a>",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "hidden": true
            },
            "id": "f21",
            "cid": "c86"
        },
        {
            "label": "<a href=\"https:\/\/itunes.apple.com\/us\/app\/epic-haiku\/id348308661?mt=8\">Download Haiku for Iphone<\/a>",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "hidden": true
            },
            "id": "f22",
            "cid": "c91"
        },
        {
            "label": "Do you share this device?",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Yes",
                        "checked": false
                    },
                    {
                        "label": "No",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "hidden": true
            },
            "id": "f11",
            "cid": "c73"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class